# Generated by Django 5.1.5 on 2025-01-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート', 'verbose_name_plural': 'カート'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'カートアイテム', 'verbose_name_plural': 'カートアイテム'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.category'),
        ),
    ]
